site_name: SEEREP
repo_url: https://github.com/agri-gaia/seerep
repo_name: agri-gaia/seerep
docs_dir: docs/mkdocs
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.tabs
  icon:
    repo: fontawesome/brands/github
  logo: imgs/DFKI-Logo_ohne_RGB_weiss.svg
  favicon: imgs/DFKI-Logo_ohne_RGB_weiss.svg
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - privacy
  - glightbox
nav:
  - SEEREP: 'index.md'
  - Getting Started:
    - Docker Deployment: 'getting_started/docker_deployment.md'
    - Python Clients: 'getting_started/python_clients.md'
    - Development Environment: 'getting_started/development_environment.md'
    - Kown Errors: 'getting_started/known_errors.md'
  - Examples:
    - Projects: 'examples/projects.md'
    - Images: 'examples/images.md'
    - Point Clouds: 'examples/point_clouds.md'
  - Reference:
    - Server Configuration: 'reference/server_configuration.md'
    - Sever Package Structure: 'reference/server_package_structure.md'
    - Python Package Structure: 'reference/python_package_structure.md'
    - Documentation Setup: 'reference/documentation_setup.md'
    - Testing Setup: 'reference/testing_setup.md'
  - About:
    - About: 'about/about.md'
    - Legal Notice: 'about/legal_notice.md'
    - Data Protection Notice: 'about/data_protection_notice.md'
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
copyright: Copyright &copy; 2021 - 2024 Deutsches Forschungszentrum für Künstliche Intelligenz GmbH (DFKI) <br>
  <a href="/seerep/mkdocs/legal-notice/index.html">Legal Notice</a> - <a href="/seerep/mkdocs/data-protection-notice/index.html">Data Protection Notice</a>
