version: "3.6"
services:
  seerep:
    image: ghcr.io/agri-gaia/seerep_server:latest
    tty: true
    container_name: seerep_server
    ports:
      # the gRPC port
      - 9090:9090
    volumes:
      # persist the data folder
      - seerep-data:/mnt/seerep-data #using docker volume
      #- /your/local/absolute/path:/mnt/seerep-data #using host folder
    environment:
      - TZ=Europe/Berlin
      - SEEREP_DATA_FOLDER=/mnt/seerep-data/
      - SEEREP_LOG_PATH=/mnt/seerep-data/log
      - SEEREP_LOG_LEVEL=info
volumes:
  seerep-data:
