# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PointCloud2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PointField_pb2 as PointField__pb2
import Header_pb2 as Header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PointCloud2.proto',
  package='ag.ros',
  syntax='proto3',
  serialized_pb=_b('\n\x11PointCloud2.proto\x12\x06\x61g.ros\x1a\x10PointField.proto\x1a\x0cHeader.proto\"\xcc\x01\n\x0bPointCloud2\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.ag.ros.Header\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\r\n\x05width\x18\x03 \x01(\r\x12\"\n\x06\x66ields\x18\x04 \x03(\x0b\x32\x12.ag.ros.PointField\x12\x14\n\x0cis_bigendian\x18\x05 \x01(\x08\x12\x12\n\npoint_step\x18\x06 \x01(\r\x12\x10\n\x08row_step\x18\x07 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x08 \x01(\x0c\x12\x10\n\x08is_dense\x18\t \x01(\x08\x62\x06proto3')
  ,
  dependencies=[PointField__pb2.DESCRIPTOR,Header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POINTCLOUD2 = _descriptor.Descriptor(
  name='PointCloud2',
  full_name='ag.ros.PointCloud2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ag.ros.PointCloud2.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='ag.ros.PointCloud2.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='ag.ros.PointCloud2.width', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fields', full_name='ag.ros.PointCloud2.fields', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_bigendian', full_name='ag.ros.PointCloud2.is_bigendian', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point_step', full_name='ag.ros.PointCloud2.point_step', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='row_step', full_name='ag.ros.PointCloud2.row_step', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='ag.ros.PointCloud2.data', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_dense', full_name='ag.ros.PointCloud2.is_dense', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=266,
)

_POINTCLOUD2.fields_by_name['header'].message_type = Header__pb2._HEADER
_POINTCLOUD2.fields_by_name['fields'].message_type = PointField__pb2._POINTFIELD
DESCRIPTOR.message_types_by_name['PointCloud2'] = _POINTCLOUD2

PointCloud2 = _reflection.GeneratedProtocolMessageType('PointCloud2', (_message.Message,), dict(
  DESCRIPTOR = _POINTCLOUD2,
  __module__ = 'PointCloud2_pb2'
  # @@protoc_insertion_point(class_scope:ag.ros.PointCloud2)
  ))
_sym_db.RegisterMessage(PointCloud2)


# @@protoc_insertion_point(module_scope)
