var dir_e06fbc69d7bd8cd1b53582adfa7adbda =
[
    [ "boundingbox.proto", "boundingbox_8proto.html", null ],
    [ "camera_intrinsics.proto", "camera__intrinsics_8proto.html", null ],
    [ "camera_intrinsics_query.proto", "camera__intrinsics__query_8proto.html", null ],
    [ "datatype.proto", "datatype_8proto.html", null ],
    [ "frame_query.proto", "frame__query_8proto.html", null ],
    [ "geodetic_coordinates.proto", "geodetic__coordinates_8proto.html", null ],
    [ "header.proto", "header_8proto.html", null ],
    [ "image.proto", "image_8proto.html", null ],
    [ "label.proto", "label_8proto.html", null ],
    [ "label_category.proto", "label__category_8proto.html", null ],
    [ "point.proto", "point_8proto.html", null ],
    [ "point2d.proto", "point2d_8proto.html", null ],
    [ "point_cloud_2.proto", "point__cloud__2_8proto.html", null ],
    [ "point_field.proto", "point__field_8proto.html", null ],
    [ "point_stamped.proto", "point__stamped_8proto.html", null ],
    [ "polygon2d.proto", "polygon2d_8proto.html", null ],
    [ "project_info.proto", "project__info_8proto.html", null ],
    [ "project_infos.proto", "project__infos_8proto.html", null ],
    [ "projectCreation.proto", "projectCreation_8proto.html", null ],
    [ "quaternion.proto", "quaternion_8proto.html", null ],
    [ "query.proto", "query_8proto.html", null ],
    [ "region_of_interest.proto", "region__of__interest_8proto.html", null ],
    [ "server_response.proto", "server__response_8proto.html", null ],
    [ "string_vector.proto", "string__vector_8proto.html", null ],
    [ "time_interval.proto", "time__interval_8proto.html", null ],
    [ "timestamp.proto", "timestamp_8proto.html", null ],
    [ "transform.proto", "transform_8proto.html", null ],
    [ "transform_stamped.proto", "transform__stamped_8proto.html", null ],
    [ "transform_stamped_query.proto", "transform__stamped__query_8proto.html", null ],
    [ "uuid_datatype_pair.proto", "uuid__datatype__pair_8proto.html", null ],
    [ "uuid_datatype_with_category.proto", "uuid__datatype__with__category_8proto.html", null ],
    [ "vector3.proto", "vector3_8proto.html", null ]
];